# Generated by Django 6.0.2 on 2026-02-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='target_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
