# Generated by Django 6.0.2 on 2026-02-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_household_target_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_threshold', models.PositiveIntegerField(default=1)),
                ('expiry_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='uniq_household_invited_email',
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='household',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting', to='accounts.household'),
        ),
    ]
