# Generated by Django 6.0.2 on 2026-02-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alertsetting_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('household', 'invited_email'), name='uniq_household_invited_email'),
        ),
    ]
