# Generated by Django 6.0.2 on 2026-02-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_memo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', '赤'), ('pink', 'ピンク'), ('orange', 'オレンジ'), ('yellow', '黄色'), ('lime', '黄緑'), ('green', '緑'), ('sky', '水色'), ('blue', '青'), ('navy', '紺'), ('purple', '紫'), ('brown', '茶色'), ('gray', 'グレー')], default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='goal_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='goal_unit',
            field=models.CharField(choices=[('L', 'L'), ('PCS', '個')], default='PCS', max_length=10),
        ),
    ]
