# Generated by Django 6.0.2 on 2026-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_color_category_goal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='content_amount',
            field=models.FloatField(default=1.0),
        ),
    ]
