# Generated by Django 6.0.2 on 2026-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#f1e8ff', max_length=7),
        ),
    ]
