# Generated by Django 6.0.2 on 2026-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#f1e8ff', help_text='例：#ffcc00', max_length=7),
        ),
    ]
