# Generated by Django 6.0.2 on 2026-03-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='商品画像'),
        ),
    ]
