# Generated by Django 6.0.2 on 2026-03-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventoryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='target_unit',
            field=models.CharField(choices=[('L', 'L'), ('PCS', '個')], default='PCS', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', '赤'), ('pink', 'ピンク'), ('orange', 'オレンジ'), ('yellow', '黄色'), ('yellowgreen', '黄緑'), ('green', '緑'), ('lightblue', '水色'), ('blue', '青'), ('navy', '紺'), ('purple', '紫'), ('brown', '茶色'), ('gray', 'グレー')], default='blue', max_length=20),
        ),
    ]
