# Generated by Django 6.0.2 on 2026-03-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_category_description_category_target_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='target_amount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='target_unit',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#f1e8ff', help_text='例：#ffcc00', max_length=7),
        ),
    ]
