# Generated by Django 6.0.2 on 2026-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_category_options_remove_category_target_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='説明'),
        ),
    ]
