# Generated by Django 6.0.2 on 2026-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
