# Generated by Django 6.0.2 on 2026-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventoryitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
