# Generated by Django 6.0.2 on 2026-03-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryitem_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='content_unit',
            field=models.CharField(choices=[('L', 'L'), ('個', '個')], default='個', max_length=10, verbose_name='内容量の単位'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_unit',
            field=models.CharField(choices=[('本', '本'), ('個', '個')], default='個', max_length=10, verbose_name='個数の単位'),
        ),
    ]
